name: Actualizar clima diariamente

on:
  schedule:
    - cron: '0 7 * * *'  # Se ejecuta todos los días a las 7:00 AM UTC
  workflow_dispatch:     # Permite ejecutarlo manualmente desde GitHub

jobs:
  update-clima:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar script para actualizar clima
        run: python update_clima.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Configurar git para push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Hacer commit y push
        run: |
          git add clima.json
          git commit -m "Actualización diaria del clima" || echo "No hay cambios para commitear"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main


