name: Actualizar clima (sin push)

on:
  schedule:
    - cron: '0 7 * * *'  # Todos los días a las 7:00 AM UTC
  workflow_dispatch:

jobs:
  update-clima:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar script para actualizar clima
        run: python update_clima.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
